<?php

namespace App\Collections;

use App\Types\Collection;

class CountryCollection extends Collection
{
    /**
     * The field to sort by.
     *
     */
    protected string $sort = 'name';

    /**
     * The items within the collection.
     *
     */
    protected function source() : array
    {
        return [
            (object) ['id' => 1,   'code' => 'AF', 'flag' => '🇦🇫', 'currency' => 'AFN', 'name' => 'Afghanistan'],
            (object) ['id' => 2,   'code' => 'AX', 'flag' => '🇦🇽', 'currency' => 'EUR', 'name' => 'Åland Islands'],
            (object) ['id' => 3,   'code' => 'AL', 'flag' => '🇦🇱', 'currency' => 'ALL', 'name' => 'Albania'],
            (object) ['id' => 4,   'code' => 'DZ', 'flag' => '🇩🇿', 'currency' => 'DZD', 'name' => 'Algeria'],
            (object) ['id' => 5,   'code' => 'AS', 'flag' => '🇦🇸', 'currency' => 'USD', 'name' => 'American Samoa'],
            (object) ['id' => 6,   'code' => 'AD', 'flag' => '🇦🇩', 'currency' => 'EUR', 'name' => 'Andorra'],
            (object) ['id' => 7,   'code' => 'AO', 'flag' => '🇦🇴', 'currency' => 'AOA', 'name' => 'Angola'],
            (object) ['id' => 8,   'code' => 'AI', 'flag' => '🇦🇮', 'currency' => 'XCD', 'name' => 'Anguilla'],
            (object) ['id' => 9,   'code' => 'AQ', 'flag' => '🇦🇶', 'currency' => 'EUR', 'name' => 'Antarctica'],
            (object) ['id' => 10,  'code' => 'AG', 'flag' => '🇦🇬', 'currency' => 'XCD', 'name' => 'Antigua and Barbuda'],
            (object) ['id' => 11,  'code' => 'AR', 'flag' => '🇦🇷', 'currency' => 'ARS', 'name' => 'Argentina'],
            (object) ['id' => 12,  'code' => 'AM', 'flag' => '🇦🇲', 'currency' => 'AMD', 'name' => 'Armenia'],
            (object) ['id' => 13,  'code' => 'AW', 'flag' => '🇦🇼', 'currency' => 'AWG', 'name' => 'Aruba'],
            (object) ['id' => 14,  'code' => 'AU', 'flag' => '🇦🇺', 'currency' => 'AUD', 'name' => 'Australia'],
            (object) ['id' => 15,  'code' => 'AT', 'flag' => '🇦🇹', 'currency' => 'EUR', 'name' => 'Austria'],
            (object) ['id' => 16,  'code' => 'AZ', 'flag' => '🇦🇿', 'currency' => 'AZN', 'name' => 'Azerbaijan'],
            (object) ['id' => 17,  'code' => 'BS', 'flag' => '🇧🇸', 'currency' => 'BSD', 'name' => 'Bahamas'],
            (object) ['id' => 18,  'code' => 'BH', 'flag' => '🇧🇭', 'currency' => 'BHD', 'name' => 'Bahrain'],
            (object) ['id' => 19,  'code' => 'BD', 'flag' => '🇧🇩', 'currency' => 'BDT', 'name' => 'Bangladesh'],
            (object) ['id' => 20,  'code' => 'BB', 'flag' => '🇧🇧', 'currency' => 'BBD', 'name' => 'Barbados'],
            (object) ['id' => 21,  'code' => 'BY', 'flag' => '🇧🇾', 'currency' => 'BYN', 'name' => 'Belarus'],
            (object) ['id' => 22,  'code' => 'BE', 'flag' => '🇧🇪', 'currency' => 'EUR', 'name' => 'Belgium'],
            (object) ['id' => 23,  'code' => 'BZ', 'flag' => '🇧🇿', 'currency' => 'BZD', 'name' => 'Belize'],
            (object) ['id' => 24,  'code' => 'BJ', 'flag' => '🇧🇯', 'currency' => 'XOF', 'name' => 'Benin'],
            (object) ['id' => 25,  'code' => 'BM', 'flag' => '🇧🇲', 'currency' => 'BMD', 'name' => 'Bermuda'],
            (object) ['id' => 26,  'code' => 'BT', 'flag' => '🇧🇹', 'currency' => 'BTN', 'name' => 'Bhutan'],
            (object) ['id' => 27,  'code' => 'BO', 'flag' => '🇧🇴', 'currency' => 'BOB', 'name' => 'Bolivia'],
            (object) ['id' => 28,  'code' => 'BQ', 'flag' => '🇧🇶', 'currency' => 'USD', 'name' => 'Bonaire, Sint Eustatius and Saba'],
            (object) ['id' => 29,  'code' => 'BA', 'flag' => '🇧🇦', 'currency' => 'BAM', 'name' => 'Bosnia and Herzegovina'],
            (object) ['id' => 30,  'code' => 'BW', 'flag' => '🇧🇼', 'currency' => 'BWP', 'name' => 'Botswana'],
            (object) ['id' => 31,  'code' => 'BV', 'flag' => '🇧🇻', 'currency' => 'NOK', 'name' => 'Bouvet Island'],
            (object) ['id' => 32,  'code' => 'BR', 'flag' => '🇧🇷', 'currency' => 'BRL', 'name' => 'Brazil'],
            (object) ['id' => 33,  'code' => 'IO', 'flag' => '🇮🇴', 'currency' => 'USD', 'name' => 'British Indian Ocean Territory'],
            (object) ['id' => 34,  'code' => 'VG', 'flag' => '🇻🇬', 'currency' => 'USD', 'name' => 'British Virgin Islands'],
            (object) ['id' => 35,  'code' => 'BN', 'flag' => '🇧🇳', 'currency' => 'BND', 'name' => 'Brunei'],
            (object) ['id' => 36,  'code' => 'BG', 'flag' => '🇧🇬', 'currency' => 'BGN', 'name' => 'Bulgaria'],
            (object) ['id' => 37,  'code' => 'BF', 'flag' => '🇧🇫', 'currency' => 'XOF', 'name' => 'Burkina Faso'],
            (object) ['id' => 38,  'code' => 'BI', 'flag' => '🇧🇮', 'currency' => 'BIF', 'name' => 'Burundi'],
            (object) ['id' => 39,  'code' => 'KH', 'flag' => '🇰🇭', 'currency' => 'KHR', 'name' => 'Cambodia'],
            (object) ['id' => 40,  'code' => 'CM', 'flag' => '🇨🇲', 'currency' => 'XAF', 'name' => 'Cameroon'],
            (object) ['id' => 41,  'code' => 'CA', 'flag' => '🇨🇦', 'currency' => 'CAD', 'name' => 'Canada'],
            (object) ['id' => 42,  'code' => 'CV', 'flag' => '🇨🇻', 'currency' => 'CVE', 'name' => 'Cape Verde'],
            (object) ['id' => 43,  'code' => 'KY', 'flag' => '🇰🇾', 'currency' => 'KYD', 'name' => 'Cayman Islands'],
            (object) ['id' => 44,  'code' => 'CF', 'flag' => '🇨🇫', 'currency' => 'XAF', 'name' => 'Central African Republic'],
            (object) ['id' => 45,  'code' => 'TD', 'flag' => '🇹🇩', 'currency' => 'XAF', 'name' => 'Chad'],
            (object) ['id' => 46,  'code' => 'CL', 'flag' => '🇨🇱', 'currency' => 'CLP', 'name' => 'Chile'],
            (object) ['id' => 47,  'code' => 'CN', 'flag' => '🇨🇳', 'currency' => 'CNY', 'name' => 'China'],
            (object) ['id' => 48,  'code' => 'CX', 'flag' => '🇨🇽', 'currency' => 'AUD', 'name' => 'Christmas Island'],
            (object) ['id' => 49,  'code' => 'CC', 'flag' => '🇨🇨', 'currency' => 'AUD', 'name' => 'Cocos (Keeling) Islands'],
            (object) ['id' => 50,  'code' => 'CO', 'flag' => '🇨🇴', 'currency' => 'COP', 'name' => 'Colombia'],
            (object) ['id' => 51,  'code' => 'KM', 'flag' => '🇰🇲', 'currency' => 'KMF', 'name' => 'Comoros'],
            (object) ['id' => 52,  'code' => 'CG', 'flag' => '🇨🇬', 'currency' => 'XAF', 'name' => 'Congo'],
            (object) ['id' => 53,  'code' => 'CK', 'flag' => '🇨🇰', 'currency' => 'NZD', 'name' => 'Cook Islands'],
            (object) ['id' => 54,  'code' => 'CR', 'flag' => '🇨🇷', 'currency' => 'CRC', 'name' => 'Costa Rica'],
            (object) ['id' => 55,  'code' => 'HR', 'flag' => '🇭🇷', 'currency' => 'HRK', 'name' => 'Croatia'],
            (object) ['id' => 56,  'code' => 'CW', 'flag' => '🇨🇼', 'currency' => 'ANG', 'name' => 'Curaçao'],
            (object) ['id' => 57,  'code' => 'CY', 'flag' => '🇨🇾', 'currency' => 'EUR', 'name' => 'Cyprus'],
            (object) ['id' => 58,  'code' => 'CZ', 'flag' => '🇨🇿', 'currency' => 'CZK', 'name' => 'Czech Republic'],
            (object) ['id' => 59,  'code' => 'DK', 'flag' => '🇩🇰', 'currency' => 'DKK', 'name' => 'Denmark'],
            (object) ['id' => 60,  'code' => 'DJ', 'flag' => '🇩🇯', 'currency' => 'DJF', 'name' => 'Djibouti'],
            (object) ['id' => 61,  'code' => 'DM', 'flag' => '🇩🇲', 'currency' => 'XCD', 'name' => 'Dominica'],
            (object) ['id' => 62,  'code' => 'DO', 'flag' => '🇩🇴', 'currency' => 'DOP', 'name' => 'Dominican Republic'],
            (object) ['id' => 63,  'code' => 'EC', 'flag' => '🇪🇨', 'currency' => 'USD', 'name' => 'Ecuador'],
            (object) ['id' => 64,  'code' => 'EG', 'flag' => '🇪🇬', 'currency' => 'EGP', 'name' => 'Egypt'],
            (object) ['id' => 65,  'code' => 'SV', 'flag' => '🇸🇻', 'currency' => 'USD', 'name' => 'El Salvador'],
            (object) ['id' => 66,  'code' => 'GQ', 'flag' => '🇬🇶', 'currency' => 'XAF', 'name' => 'Equatorial Guinea'],
            (object) ['id' => 67,  'code' => 'ER', 'flag' => '🇪🇷', 'currency' => 'ERN', 'name' => 'Eritrea'],
            (object) ['id' => 68,  'code' => 'EE', 'flag' => '🇪🇪', 'currency' => 'EUR', 'name' => 'Estonia'],
            (object) ['id' => 69,  'code' => 'ET', 'flag' => '🇪🇹', 'currency' => 'ETB', 'name' => 'Ethiopia'],
            (object) ['id' => 70,  'code' => 'FK', 'flag' => '🇫🇰', 'currency' => 'FKP', 'name' => 'Falkland Islands'],
            (object) ['id' => 71,  'code' => 'FO', 'flag' => '🇫🇴', 'currency' => 'DKK', 'name' => 'Faroe Islands'],
            (object) ['id' => 72,  'code' => 'FJ', 'flag' => '🇫🇯', 'currency' => 'FJD', 'name' => 'Fiji'],
            (object) ['id' => 73,  'code' => 'FI', 'flag' => '🇫🇮', 'currency' => 'EUR', 'name' => 'Finland'],
            (object) ['id' => 74,  'code' => 'FR', 'flag' => '🇫🇷', 'currency' => 'EUR', 'name' => 'France'],
            (object) ['id' => 75,  'code' => 'GF', 'flag' => '🇬🇫', 'currency' => 'EUR', 'name' => 'French Guiana'],
            (object) ['id' => 76,  'code' => 'PF', 'flag' => '🇵🇫', 'currency' => 'XPF', 'name' => 'French Polynesia'],
            (object) ['id' => 77,  'code' => 'TF', 'flag' => '🇹🇫', 'currency' => 'EUR', 'name' => 'French Southern Territories'],
            (object) ['id' => 78,  'code' => 'GA', 'flag' => '🇬🇦', 'currency' => 'XAF', 'name' => 'Gabon'],
            (object) ['id' => 79,  'code' => 'GM', 'flag' => '🇬🇲', 'currency' => 'GMD', 'name' => 'Gambia'],
            (object) ['id' => 80,  'code' => 'GE', 'flag' => '🇬🇪', 'currency' => 'GEL', 'name' => 'Georgia'],
            (object) ['id' => 81,  'code' => 'DE', 'flag' => '🇩🇪', 'currency' => 'EUR', 'name' => 'Germany'],
            (object) ['id' => 82,  'code' => 'GH', 'flag' => '🇬🇭', 'currency' => 'GHS', 'name' => 'Ghana'],
            (object) ['id' => 83,  'code' => 'GI', 'flag' => '🇬🇮', 'currency' => 'GIP', 'name' => 'Gibraltar'],
            (object) ['id' => 84,  'code' => 'GR', 'flag' => '🇬🇷', 'currency' => 'EUR', 'name' => 'Greece'],
            (object) ['id' => 85,  'code' => 'GL', 'flag' => '🇬🇱', 'currency' => 'DKK', 'name' => 'Greenland'],
            (object) ['id' => 86,  'code' => 'GD', 'flag' => '🇬🇩', 'currency' => 'XCD', 'name' => 'Grenada'],
            (object) ['id' => 87,  'code' => 'GP', 'flag' => '🇬🇵', 'currency' => 'EUR', 'name' => 'Guadeloupe'],
            (object) ['id' => 88,  'code' => 'GU', 'flag' => '🇬🇺', 'currency' => 'USD', 'name' => 'Guam'],
            (object) ['id' => 89,  'code' => 'GT', 'flag' => '🇬🇹', 'currency' => 'GTQ', 'name' => 'Guatemala'],
            (object) ['id' => 90,  'code' => 'GG', 'flag' => '🇬🇬', 'currency' => 'GBP', 'name' => 'Guernsey'],
            (object) ['id' => 91,  'code' => 'GN', 'flag' => '🇬🇳', 'currency' => 'GNF', 'name' => 'Guinea'],
            (object) ['id' => 92,  'code' => 'GW', 'flag' => '🇬🇼', 'currency' => 'XOF', 'name' => 'Guinea-Bissau'],
            (object) ['id' => 93,  'code' => 'GY', 'flag' => '🇬🇾', 'currency' => 'GYD', 'name' => 'Guyana'],
            (object) ['id' => 94,  'code' => 'HT', 'flag' => '🇭🇹', 'currency' => 'HTG', 'name' => 'Haiti'],
            (object) ['id' => 95,  'code' => 'HM', 'flag' => '🇭🇲', 'currency' => 'AUD', 'name' => 'Heard Island and McDonald Islands'],
            (object) ['id' => 96,  'code' => 'VA', 'flag' => '🇻🇦', 'currency' => 'EUR', 'name' => 'Holy See / Vatican City State'],
            (object) ['id' => 97,  'code' => 'HN', 'flag' => '🇭🇳', 'currency' => 'HNL', 'name' => 'Honduras'],
            (object) ['id' => 98,  'code' => 'HK', 'flag' => '🇭🇰', 'currency' => 'HKD', 'name' => 'Hong Kong'],
            (object) ['id' => 99,  'code' => 'HU', 'flag' => '🇭🇺', 'currency' => 'HUF', 'name' => 'Hungary'],
            (object) ['id' => 100, 'code' => 'IS', 'flag' => '🇮🇸', 'currency' => 'ISK', 'name' => 'Iceland'],
            (object) ['id' => 101, 'code' => 'IN', 'flag' => '🇮🇳', 'currency' => 'INR', 'name' => 'India'],
            (object) ['id' => 102, 'code' => 'ID', 'flag' => '🇮🇩', 'currency' => 'IDR', 'name' => 'Indonesia'],
            (object) ['id' => 103, 'code' => 'IQ', 'flag' => '🇮🇶', 'currency' => 'IQD', 'name' => 'Iraq'],
            (object) ['id' => 104, 'code' => 'IE', 'flag' => '🇮🇪', 'currency' => 'EUR', 'name' => 'Ireland'],
            (object) ['id' => 105, 'code' => 'IM', 'flag' => '🇮🇲', 'currency' => 'USD', 'name' => 'Isle of Man'],
            (object) ['id' => 106, 'code' => 'IL', 'flag' => '🇮🇱', 'currency' => 'ILS', 'name' => 'Israel'],
            (object) ['id' => 107, 'code' => 'IT', 'flag' => '🇮🇹', 'currency' => 'EUR', 'name' => 'Italy'],
            (object) ['id' => 108, 'code' => 'IC', 'flag' => '🇨🇮', 'currency' => 'XAF', 'name' => 'Ivory Coast'],
            (object) ['id' => 109, 'code' => 'JM', 'flag' => '🇯🇲', 'currency' => 'JMD', 'name' => 'Jamaica'],
            (object) ['id' => 110, 'code' => 'JP', 'flag' => '🇯🇵', 'currency' => 'JPY', 'name' => 'Japan'],
            (object) ['id' => 111, 'code' => 'JE', 'flag' => '🇯🇪', 'currency' => 'GBP', 'name' => 'Jersey'],
            (object) ['id' => 112, 'code' => 'JO', 'flag' => '🇯🇴', 'currency' => 'JOD', 'name' => 'Jordan'],
            (object) ['id' => 113, 'code' => 'KZ', 'flag' => '🇰🇿', 'currency' => 'KZT', 'name' => 'Kazakhstan'],
            (object) ['id' => 114, 'code' => 'KE', 'flag' => '🇰🇪', 'currency' => 'KES', 'name' => 'Kenya'],
            (object) ['id' => 115, 'code' => 'KI', 'flag' => '🇰🇮', 'currency' => 'AUD', 'name' => 'Kiribati'],
            (object) ['id' => 116, 'code' => 'KV', 'flag' => '🇽🇰', 'currency' => 'EUR', 'name' => 'Kosovo'],
            (object) ['id' => 117, 'code' => 'KW', 'flag' => '🇰🇼', 'currency' => 'KWD', 'name' => 'Kuwait'],
            (object) ['id' => 118, 'code' => 'KG', 'flag' => '🇰🇬', 'currency' => 'KGS', 'name' => 'Kyrgyzstan'],
            (object) ['id' => 119, 'code' => 'LA', 'flag' => '🇱🇦', 'currency' => 'LAK', 'name' => 'Laos'],
            (object) ['id' => 120, 'code' => 'LV', 'flag' => '🇱🇻', 'currency' => 'EUR', 'name' => 'Latvia'],
            (object) ['id' => 121, 'code' => 'LB', 'flag' => '🇱🇧', 'currency' => 'LBP', 'name' => 'Lebanon'],
            (object) ['id' => 122, 'code' => 'LS', 'flag' => '🇱🇸', 'currency' => 'LSL', 'name' => 'Lesotho'],
            (object) ['id' => 123, 'code' => 'LR', 'flag' => '🇱🇷', 'currency' => 'LRD', 'name' => 'Liberia'],
            (object) ['id' => 124, 'code' => 'LY', 'flag' => '🇱🇾', 'currency' => 'LYD', 'name' => 'Libya'],
            (object) ['id' => 125, 'code' => 'LI', 'flag' => '🇱🇮', 'currency' => 'CHF', 'name' => 'Liechtenstein'],
            (object) ['id' => 126, 'code' => 'LT', 'flag' => '🇱🇹', 'currency' => 'EUR', 'name' => 'Lithuania'],
            (object) ['id' => 127, 'code' => 'LU', 'flag' => '🇱🇺', 'currency' => 'EUR', 'name' => 'Luxembourg'],
            (object) ['id' => 128, 'code' => 'MO', 'flag' => '🇲🇴', 'currency' => 'MOP', 'name' => 'Macao'],
            (object) ['id' => 129, 'code' => 'MK', 'flag' => '🇲🇰', 'currency' => 'MKD', 'name' => 'Macedonia'],
            (object) ['id' => 130, 'code' => 'MG', 'flag' => '🇲🇬', 'currency' => 'MGA', 'name' => 'Madagascar'],
            (object) ['id' => 131, 'code' => 'MW', 'flag' => '🇲🇼', 'currency' => 'MWK', 'name' => 'Malawi'],
            (object) ['id' => 132, 'code' => 'MY', 'flag' => '🇲🇾', 'currency' => 'MYR', 'name' => 'Malaysia'],
            (object) ['id' => 133, 'code' => 'MV', 'flag' => '🇲🇻', 'currency' => 'MVR', 'name' => 'Maldives'],
            (object) ['id' => 134, 'code' => 'ML', 'flag' => '🇲🇱', 'currency' => 'XOF', 'name' => 'Mali'],
            (object) ['id' => 135, 'code' => 'MT', 'flag' => '🇲🇹', 'currency' => 'EUR', 'name' => 'Malta'],
            (object) ['id' => 136, 'code' => 'MH', 'flag' => '🇲🇭', 'currency' => 'USD', 'name' => 'Marshall Islands'],
            (object) ['id' => 137, 'code' => 'MQ', 'flag' => '🇲🇶', 'currency' => 'EUR', 'name' => 'Martinique'],
            (object) ['id' => 138, 'code' => 'MR', 'flag' => '🇲🇷', 'currency' => 'MRO', 'name' => 'Mauritania'],
            (object) ['id' => 139, 'code' => 'MU', 'flag' => '🇲🇺', 'currency' => 'MUR', 'name' => 'Mauritius'],
            (object) ['id' => 140, 'code' => 'YT', 'flag' => '🇾🇹', 'currency' => 'EUR', 'name' => 'Mayotte'],
            (object) ['id' => 141, 'code' => 'MX', 'flag' => '🇲🇽', 'currency' => 'MXN', 'name' => 'Mexico'],
            (object) ['id' => 142, 'code' => 'FM', 'flag' => '🇫🇲', 'currency' => 'USD', 'name' => 'Micronesia'],
            (object) ['id' => 143, 'code' => 'MD', 'flag' => '🇲🇩', 'currency' => 'MDL', 'name' => 'Moldova'],
            (object) ['id' => 144, 'code' => 'MC', 'flag' => '🇲🇨', 'currency' => 'EUR', 'name' => 'Monaco'],
            (object) ['id' => 145, 'code' => 'MN', 'flag' => '🇲🇳', 'currency' => 'MNT', 'name' => 'Mongolia'],
            (object) ['id' => 146, 'code' => 'ME', 'flag' => '🇲🇪', 'currency' => 'EUR', 'name' => 'Montenegro'],
            (object) ['id' => 147, 'code' => 'MS', 'flag' => '🇲🇸', 'currency' => 'XCD', 'name' => 'Montserrat'],
            (object) ['id' => 148, 'code' => 'MA', 'flag' => '🇲🇦', 'currency' => 'MAD', 'name' => 'Morocco'],
            (object) ['id' => 149, 'code' => 'MZ', 'flag' => '🇲🇿', 'currency' => 'MZM', 'name' => 'Mozambique'],
            (object) ['id' => 150, 'code' => 'MM', 'flag' => '🇲🇲', 'currency' => 'MMK', 'name' => 'Myanmar'],
            (object) ['id' => 151, 'code' => 'NA', 'flag' => '🇳🇦', 'currency' => 'NAD', 'name' => 'Namibia'],
            (object) ['id' => 152, 'code' => 'NR', 'flag' => '🇳🇷', 'currency' => 'AUD', 'name' => 'Nauru'],
            (object) ['id' => 153, 'code' => 'NP', 'flag' => '🇳🇵', 'currency' => 'NPR', 'name' => 'Nepal'],
            (object) ['id' => 154, 'code' => 'AN', 'flag' => '🇳🇱', 'currency' => 'ANG', 'name' => 'Netherlands Antilles'],
            (object) ['id' => 155, 'code' => 'NC', 'flag' => '🇳🇨', 'currency' => 'XPF', 'name' => 'New Caledonia'],
            (object) ['id' => 156, 'code' => 'NZ', 'flag' => '🇳🇿', 'currency' => 'NZD', 'name' => 'New Zealand'],
            (object) ['id' => 157, 'code' => 'NI', 'flag' => '🇳🇮', 'currency' => 'NIO', 'name' => 'Nicaragua'],
            (object) ['id' => 158, 'code' => 'NE', 'flag' => '🇳🇪', 'currency' => 'XOF', 'name' => 'Niger'],
            (object) ['id' => 159, 'code' => 'NG', 'flag' => '🇳🇬', 'currency' => 'NGN', 'name' => 'Nigeria'],
            (object) ['id' => 160, 'code' => 'NU', 'flag' => '🇳🇺', 'currency' => 'NZD', 'name' => 'Niue'],
            (object) ['id' => 161, 'code' => 'NF', 'flag' => '🇳🇫', 'currency' => 'AUD', 'name' => 'Norfolk Island'],
            (object) ['id' => 162, 'code' => 'MP', 'flag' => '🇲🇵', 'currency' => 'USD', 'name' => 'Northern Mariana Islands'],
            (object) ['id' => 163, 'code' => 'NO', 'flag' => '🇳🇴', 'currency' => 'NOK', 'name' => 'Norway'],
            (object) ['id' => 164, 'code' => 'OM', 'flag' => '🇴🇲', 'currency' => 'OMR', 'name' => 'Oman'],
            (object) ['id' => 165, 'code' => 'PK', 'flag' => '🇵🇰', 'currency' => 'PKR', 'name' => 'Pakistan'],
            (object) ['id' => 166, 'code' => 'PW', 'flag' => '🇵🇼', 'currency' => 'USD', 'name' => 'Palau'],
            (object) ['id' => 167, 'code' => 'PS', 'flag' => '🇵🇸', 'currency' => 'ILS', 'name' => 'Palestine,of'],
            (object) ['id' => 168, 'code' => 'PA', 'flag' => '🇵🇦', 'currency' => 'USD', 'name' => 'Panama'],
            (object) ['id' => 169, 'code' => 'PG', 'flag' => '🇵🇬', 'currency' => 'PGK', 'name' => 'Papua New Guinea'],
            (object) ['id' => 170, 'code' => 'PY', 'flag' => '🇵🇾', 'currency' => 'PYG', 'name' => 'Paraguay'],
            (object) ['id' => 171, 'code' => 'PE', 'flag' => '🇵🇪', 'currency' => 'PEN', 'name' => 'Peru'],
            (object) ['id' => 172, 'code' => 'PH', 'flag' => '🇵🇭', 'currency' => 'PHP', 'name' => 'Philippines'],
            (object) ['id' => 173, 'code' => 'PL', 'flag' => '🇵🇱', 'currency' => 'PLN', 'name' => 'Poland'],
            (object) ['id' => 174, 'code' => 'PT', 'flag' => '🇵🇹', 'currency' => 'EUR', 'name' => 'Portugal'],
            (object) ['id' => 175, 'code' => 'PR', 'flag' => '🇵🇷', 'currency' => 'USD', 'name' => 'Puerto Rico'],
            (object) ['id' => 176, 'code' => 'QA', 'flag' => '🇶🇦', 'currency' => 'QAR', 'name' => 'Qatar'],
            (object) ['id' => 177, 'code' => 'RE', 'flag' => '🇷🇪', 'currency' => 'EUR', 'name' => 'Reunion'],
            (object) ['id' => 178, 'code' => 'RO', 'flag' => '🇷🇴', 'currency' => 'RON', 'name' => 'Romania'],
            (object) ['id' => 179, 'code' => 'RU', 'flag' => '🇷🇺', 'currency' => 'RUB', 'name' => 'Russia'],
            (object) ['id' => 180, 'code' => 'RW', 'flag' => '🇷🇼', 'currency' => 'RWF', 'name' => 'Rwanda'],
            (object) ['id' => 181, 'code' => 'BL', 'flag' => '🇧🇱', 'currency' => 'EUR', 'name' => 'Saint Barthélemy'],
            (object) ['id' => 182, 'code' => 'SH', 'flag' => '🇸🇭', 'currency' => 'SHP', 'name' => 'Saint Helena'],
            (object) ['id' => 183, 'code' => 'KN', 'flag' => '🇰🇳', 'currency' => 'USD', 'name' => 'Saint Kitts and Nevis'],
            (object) ['id' => 184, 'code' => 'LC', 'flag' => '🇱🇨', 'currency' => 'XCD', 'name' => 'Saint Lucia'],
            (object) ['id' => 185, 'code' => 'MF', 'flag' => '🇲🇫', 'currency' => 'USD', 'name' => 'Saint Martin'],
            (object) ['id' => 186, 'code' => 'PM', 'flag' => '🇵🇲', 'currency' => 'EUR', 'name' => 'Saint Pierre and Miquelon'],
            (object) ['id' => 187, 'code' => 'VC', 'flag' => '🇻🇨', 'currency' => 'XCD', 'name' => 'Saint Vincent and the Grenadines'],
            (object) ['id' => 188, 'code' => 'WS', 'flag' => '🇼🇸', 'currency' => 'WST', 'name' => 'Samoa'],
            (object) ['id' => 189, 'code' => 'SM', 'flag' => '🇸🇲', 'currency' => 'EUR', 'name' => 'San Marino'],
            (object) ['id' => 190, 'code' => 'ST', 'flag' => '🇸🇹', 'currency' => 'STD', 'name' => 'Sao Tome and Principe'],
            (object) ['id' => 191, 'code' => 'SA', 'flag' => '🇸🇦', 'currency' => 'SAR', 'name' => 'Saudi Arabia'],
            (object) ['id' => 192, 'code' => 'SN', 'flag' => '🇸🇳', 'currency' => 'XOF', 'name' => 'Senegal'],
            (object) ['id' => 193, 'code' => 'RS', 'flag' => '🇷🇸', 'currency' => 'RSD', 'name' => 'Serbia'],
            (object) ['id' => 194, 'code' => 'SC', 'flag' => '🇸🇨', 'currency' => 'SRC', 'name' => 'Seychelles'],
            (object) ['id' => 195, 'code' => 'SL', 'flag' => '🇸🇱', 'currency' => 'SLL', 'name' => 'Sierra Leone'],
            (object) ['id' => 196, 'code' => 'SG', 'flag' => '🇸🇬', 'currency' => 'SGD', 'name' => 'Singapore'],
            (object) ['id' => 197, 'code' => 'SX', 'flag' => '🇸🇽', 'currency' => 'USD', 'name' => 'Sint Maarten'],
            (object) ['id' => 198, 'code' => 'SK', 'flag' => '🇸🇰', 'currency' => 'EUR', 'name' => 'Slovakia'],
            (object) ['id' => 199, 'code' => 'SI', 'flag' => '🇸🇮', 'currency' => 'EUR', 'name' => 'Slovenia'],
            (object) ['id' => 200, 'code' => 'SB', 'flag' => '🇸🇧', 'currency' => 'SBD', 'name' => 'Solomon Islands'],
            (object) ['id' => 201, 'code' => 'SO', 'flag' => '🇸🇴', 'currency' => 'SOS', 'name' => 'Somalia'],
            (object) ['id' => 202, 'code' => 'ZA', 'flag' => '🇿🇦', 'currency' => 'ZAR', 'name' => 'South Africa'],
            (object) ['id' => 203, 'code' => 'GS', 'flag' => '🇬🇸', 'currency' => 'FKP', 'name' => 'South Georgia and the South Sandwich Islands'],
            (object) ['id' => 204, 'code' => 'KR', 'flag' => '🇰🇷', 'currency' => 'KRW', 'name' => 'South Korea'],
            (object) ['id' => 205, 'code' => 'SS', 'flag' => '🇸🇸', 'currency' => 'SDG', 'name' => 'South Sudan'],
            (object) ['id' => 206, 'code' => 'ES', 'flag' => '🇪🇸', 'currency' => 'EUR', 'name' => 'Spain'],
            (object) ['id' => 207, 'code' => 'LK', 'flag' => '🇱🇰', 'currency' => 'LKR', 'name' => 'Sri Lanka'],
            (object) ['id' => 208, 'code' => 'SD', 'flag' => '🇸🇩', 'currency' => 'SDG', 'name' => 'Sudan'],
            (object) ['id' => 209, 'code' => 'SR', 'flag' => '🇸🇷', 'currency' => 'SRD', 'name' => 'Suriname'],
            (object) ['id' => 210, 'code' => 'SJ', 'flag' => '🇸🇯', 'currency' => 'NOK', 'name' => 'Svalbard and Jan Mayen'],
            (object) ['id' => 211, 'code' => 'SZ', 'flag' => '🇸🇿', 'currency' => 'SZL', 'name' => 'Swaziland'],
            (object) ['id' => 212, 'code' => 'SE', 'flag' => '🇸🇪', 'currency' => 'SEK', 'name' => 'Sweden'],
            (object) ['id' => 213, 'code' => 'CH', 'flag' => '🇨🇭', 'currency' => 'CHF', 'name' => 'Switzerland'],
            (object) ['id' => 214, 'code' => 'TW', 'flag' => '🇹🇼', 'currency' => 'TWD', 'name' => 'Taiwan'],
            (object) ['id' => 215, 'code' => 'TJ', 'flag' => '🇹🇯', 'currency' => 'TJS', 'name' => 'Tajikistan'],
            (object) ['id' => 216, 'code' => 'TZ', 'flag' => '🇹🇿', 'currency' => 'TZS', 'name' => 'Tanzania'],
            (object) ['id' => 217, 'code' => 'TH', 'flag' => '🇹🇭', 'currency' => 'THB', 'name' => 'Thailand'],
            (object) ['id' => 218, 'code' => 'NL', 'flag' => '🇳🇱', 'currency' => 'EUR', 'name' => 'Netherlands'],
            (object) ['id' => 219, 'code' => 'TL', 'flag' => '🇹🇱', 'currency' => 'USD', 'name' => 'Timor-Leste'],
            (object) ['id' => 220, 'code' => 'TG', 'flag' => '🇹🇬', 'currency' => 'XOF', 'name' => 'Togo'],
            (object) ['id' => 221, 'code' => 'TK', 'flag' => '🇹🇰', 'currency' => 'NZD', 'name' => 'Tokelau'],
            (object) ['id' => 222, 'code' => 'TO', 'flag' => '🇹🇴', 'currency' => 'TOP', 'name' => 'Tonga'],
            (object) ['id' => 223, 'code' => 'TT', 'flag' => '🇹🇹', 'currency' => 'TTD', 'name' => 'Trinidad'],
            (object) ['id' => 224, 'code' => 'TN', 'flag' => '🇹🇳', 'currency' => 'TND', 'name' => 'Tunisia'],
            (object) ['id' => 225, 'code' => 'TR', 'flag' => '🇹🇷', 'currency' => 'TRY', 'name' => 'Turkey'],
            (object) ['id' => 226, 'code' => 'TM', 'flag' => '🇹🇲', 'currency' => 'TMT', 'name' => 'Turkmenistan'],
            (object) ['id' => 227, 'code' => 'TC', 'flag' => '🇹🇨', 'currency' => 'USD', 'name' => 'Turks and Caicos Islands'],
            (object) ['id' => 228, 'code' => 'TV', 'flag' => '🇹🇻', 'currency' => 'AUD', 'name' => 'Tuvalu'],
            (object) ['id' => 229, 'code' => 'VI', 'flag' => '🇻🇮', 'currency' => 'USD', 'name' => 'U.S. Virgin Islands'],
            (object) ['id' => 230, 'code' => 'UG', 'flag' => '🇺🇬', 'currency' => 'UGX', 'name' => 'Uganda'],
            (object) ['id' => 231, 'code' => 'UA', 'flag' => '🇺🇦', 'currency' => 'UAH', 'name' => 'Ukraine'],
            (object) ['id' => 232, 'code' => 'AE', 'flag' => '🇦🇪', 'currency' => 'AED', 'name' => 'United Arab Emirates'],
            (object) ['id' => 233, 'code' => 'GB', 'flag' => '🇬🇧', 'currency' => 'GBP', 'name' => 'United Kingdom'],
            (object) ['id' => 234, 'code' => 'US', 'flag' => '🇺🇸', 'currency' => 'USD', 'name' => 'United States'],
            (object) ['id' => 235, 'code' => 'UM', 'flag' => '🇺🇲', 'currency' => 'USD', 'name' => 'United States Minor Outlying Islands'],
            (object) ['id' => 236, 'code' => 'UY', 'flag' => '🇺🇾', 'currency' => 'UYU', 'name' => 'Uruguay'],
            (object) ['id' => 237, 'code' => 'UZ', 'flag' => '🇺🇿', 'currency' => 'UZS', 'name' => 'Uzbekistan'],
            (object) ['id' => 238, 'code' => 'VU', 'flag' => '🇻🇺', 'currency' => 'VUV', 'name' => 'Vanuatu'],
            (object) ['id' => 239, 'code' => 'VE', 'flag' => '🇻🇪', 'currency' => 'VEF', 'name' => 'Venezuela'],
            (object) ['id' => 240, 'code' => 'VN', 'flag' => '🇻🇳', 'currency' => 'VND', 'name' => 'Vietnam'],
            (object) ['id' => 241, 'code' => 'WF', 'flag' => '🇼🇫', 'currency' => 'XPF', 'name' => 'Wallis and Futuna'],
            (object) ['id' => 242, 'code' => 'EH', 'flag' => '🇪🇭', 'currency' => 'USD', 'name' => 'Western Sahara'],
            (object) ['id' => 243, 'code' => 'YE', 'flag' => '🇾🇪', 'currency' => 'YER', 'name' => 'Yemen'],
            (object) ['id' => 244, 'code' => 'CD', 'flag' => '🇨🇩', 'currency' => 'XAF', 'name' => 'Zaire'],
            (object) ['id' => 245, 'code' => 'ZM', 'flag' => '🇿🇲', 'currency' => 'ZMW', 'name' => 'Zambia'],
            (object) ['id' => 246, 'code' => 'ZW', 'flag' => '🇿🇼', 'currency' => 'ZWL', 'name' => 'Zimbabwe'],
            (object) ['id' => 247, 'code' => 'CU', 'flag' => '🇨🇺', 'currency' => 'CUP', 'name' => 'Cuba'],
        ];
    }
}
