<?php

namespace App\Collections;

use App\Types\Collection;

class CurrencyCollection extends Collection
{
    /**
     * The items within the collection.
     *
     */
    protected function source() : array
    {
        return [
            (object) ['id' => 1,   'code' => 'AFN', 'rate' => 0, 'symbol' => '؋',    'name' => 'Afghan afghani'],
            (object) ['id' => 2,   'code' => 'ALL', 'rate' => 0, 'symbol' => 'L',    'name' => 'Albanian lek'],
            (object) ['id' => 3,   'code' => 'DZD', 'rate' => 0, 'symbol' => 'د.ج',  'name' => 'Algerian dinar'],
            (object) ['id' => 4,   'code' => 'AOA', 'rate' => 0, 'symbol' => 'Kz',   'name' => 'Angolan kwanza'],
            (object) ['id' => 5,   'code' => 'ARS', 'rate' => 0, 'symbol' => '$',    'name' => 'Argentine peso'],
            (object) ['id' => 6,   'code' => 'AMD', 'rate' => 0, 'symbol' => 'դր.',  'name' => 'Armenian dram'],
            (object) ['id' => 7,   'code' => 'AWG', 'rate' => 0, 'symbol' => 'ƒ',    'name' => 'Aruban florin'],
            (object) ['id' => 8,   'code' => 'AUD', 'rate' => 0, 'symbol' => '$',    'name' => 'Australian dollar'],
            (object) ['id' => 9,   'code' => 'AZN', 'rate' => 0, 'symbol' => 'm',    'name' => 'Azerbaijani manat'],
            (object) ['id' => 10,  'code' => 'BSD', 'rate' => 0, 'symbol' => '$',    'name' => 'Bahamian dollar'],
            (object) ['id' => 11,  'code' => 'BHD', 'rate' => 0, 'symbol' => '.د.ب', 'name' => 'Bahraini dinar'],
            (object) ['id' => 12,  'code' => 'BDT', 'rate' => 0, 'symbol' => '৳',    'name' => 'Bangladeshi taka'],
            (object) ['id' => 13,  'code' => 'BBD', 'rate' => 0, 'symbol' => '$',    'name' => 'Barbados dollar'],
            (object) ['id' => 14,  'code' => 'BYR', 'rate' => 0, 'symbol' => 'Br',   'name' => 'Belarusian ruble'],
            (object) ['id' => 15,  'code' => 'BZD', 'rate' => 0, 'symbol' => '$',    'name' => 'Belize dollar'],
            (object) ['id' => 16,  'code' => 'BTN', 'rate' => 0, 'symbol' => 'Nu.',  'name' => 'Bhutanese ngultrum'],
            (object) ['id' => 17,  'code' => 'BOB', 'rate' => 0, 'symbol' => 'Bs.',  'name' => 'Boliviano'],
            (object) ['id' => 18,  'code' => 'BAM', 'rate' => 0, 'symbol' => 'КМ',   'name' => 'Bosnia and Herzegovina convertible mark'],
            (object) ['id' => 19,  'code' => 'BWP', 'rate' => 0, 'symbol' => 'P',    'name' => 'Botswana pula'],
            (object) ['id' => 20,  'code' => 'BRL', 'rate' => 0, 'symbol' => 'R$',   'name' => 'Brazilian real'],
            (object) ['id' => 21,  'code' => 'BND', 'rate' => 0, 'symbol' => '$',    'name' => 'Brunei dollar'],
            (object) ['id' => 22,  'code' => 'BGN', 'rate' => 0, 'symbol' => 'лв',   'name' => 'Bulgarian lev'],
            (object) ['id' => 23,  'code' => 'BIF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'Burundian franc'],
            (object) ['id' => 24,  'code' => 'XOF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'CFA franc BCEAO'],
            (object) ['id' => 25,  'code' => 'XAF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'CFA franc BEAC'],
            (object) ['id' => 26,  'code' => 'XPF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'CFP franc'],
            (object) ['id' => 27,  'code' => 'KHR', 'rate' => 0, 'symbol' => '៛',    'name' => 'Cambodian riel'],
            (object) ['id' => 28,  'code' => 'CAD', 'rate' => 0, 'symbol' => '$',    'name' => 'Canadian dollar'],
            (object) ['id' => 29,  'code' => 'CVE', 'rate' => 0, 'symbol' => '$',    'name' => 'Cape Verde escudo'],
            (object) ['id' => 30,  'code' => 'KYD', 'rate' => 0, 'symbol' => '$',    'name' => 'Cayman Islands dollar'],
            (object) ['id' => 31,  'code' => 'CLP', 'rate' => 0, 'symbol' => '$',    'name' => 'Chilean peso'],
            (object) ['id' => 32,  'code' => 'CNY', 'rate' => 0, 'symbol' => '¥',    'name' => 'Chinese yuan'],
            (object) ['id' => 33,  'code' => 'COP', 'rate' => 0, 'symbol' => '$',    'name' => 'Colombian peso'],
            (object) ['id' => 34,  'code' => 'KMF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'Comoro franc'],
            (object) ['id' => 35,  'code' => 'CDF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'Congolese franc'],
            (object) ['id' => 36,  'code' => 'CRC', 'rate' => 0, 'symbol' => '₡',    'name' => 'Costa Rican colon'],
            (object) ['id' => 37,  'code' => 'HRK', 'rate' => 0, 'symbol' => 'kn',   'name' => 'Croatian kuna'],
            (object) ['id' => 38,  'code' => 'CUP', 'rate' => 0, 'symbol' => '$',    'name' => 'Cuban peso'],
            (object) ['id' => 39,  'code' => 'CZK', 'rate' => 0, 'symbol' => 'Kč',   'name' => 'Czech koruna'],
            (object) ['id' => 40,  'code' => 'DKK', 'rate' => 0, 'symbol' => 'kr',   'name' => 'Danish krone'],
            (object) ['id' => 41,  'code' => 'DJF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'Djiboutian franc'],
            (object) ['id' => 42,  'code' => 'DOP', 'rate' => 0, 'symbol' => '$',    'name' => 'Dominican peso'],
            (object) ['id' => 43,  'code' => 'XCD', 'rate' => 0, 'symbol' => '$',    'name' => 'East Caribbean dollar'],
            (object) ['id' => 44,  'code' => 'EGP', 'rate' => 0, 'symbol' => 'ج.م',  'name' => 'Egyptian pound'],
            (object) ['id' => 45,  'code' => 'ERN', 'rate' => 0, 'symbol' => 'Nfk',  'name' => 'Eritrean nakfa'],
            (object) ['id' => 46,  'code' => 'ETB', 'rate' => 0, 'symbol' => 'Br',   'name' => 'Ethiopian birr'],
            (object) ['id' => 47,  'code' => 'EUR', 'rate' => 0, 'symbol' => '€',    'name' => 'Euro'],
            (object) ['id' => 48,  'code' => 'FKP', 'rate' => 0, 'symbol' => '£',    'name' => 'Falkland Islands pound'],
            (object) ['id' => 49,  'code' => 'FJD', 'rate' => 0, 'symbol' => '$',    'name' => 'Fiji dollar'],
            (object) ['id' => 50,  'code' => 'GMD', 'rate' => 0, 'symbol' => 'D',    'name' => 'Gambian dalasi'],
            (object) ['id' => 51,  'code' => 'GEL', 'rate' => 0, 'symbol' => 'ლ',    'name' => 'Georgian lari'],
            (object) ['id' => 52,  'code' => 'GHS', 'rate' => 0, 'symbol' => '₵',    'name' => 'Ghanaian cedi'],
            (object) ['id' => 53,  'code' => 'GIP', 'rate' => 0, 'symbol' => '£',    'name' => 'Gibraltar pound'],
            (object) ['id' => 54,  'code' => 'GTQ', 'rate' => 0, 'symbol' => 'Q',    'name' => 'Guatemalan quetzal'],
            (object) ['id' => 55,  'code' => 'GNF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'Guinean franc'],
            (object) ['id' => 56,  'code' => 'GYD', 'rate' => 0, 'symbol' => '$',    'name' => 'Guyanese dollar'],
            (object) ['id' => 57,  'code' => 'HTG', 'rate' => 0, 'symbol' => 'G',    'name' => 'Haitian gourde'],
            (object) ['id' => 58,  'code' => 'HNL', 'rate' => 0, 'symbol' => 'L',    'name' => 'Honduran lempira'],
            (object) ['id' => 59,  'code' => 'HKD', 'rate' => 0, 'symbol' => '$',    'name' => 'Hong Kong dollar'],
            (object) ['id' => 60,  'code' => 'HUF', 'rate' => 0, 'symbol' => 'Ft',   'name' => 'Hungarian forint'],
            (object) ['id' => 61,  'code' => 'ISK', 'rate' => 0, 'symbol' => 'kr',   'name' => 'Icelandic króna'],
            (object) ['id' => 62,  'code' => 'INR', 'rate' => 0, 'symbol' => '₹',    'name' => 'Indian rupee'],
            (object) ['id' => 63,  'code' => 'IDR', 'rate' => 0, 'symbol' => 'Rp',   'name' => 'Indonesian rupiah'],
            (object) ['id' => 64,  'code' => 'IRR', 'rate' => 0, 'symbol' => '﷼',    'name' => 'Iranian rial'],
            (object) ['id' => 65,  'code' => 'IQD', 'rate' => 0, 'symbol' => 'ع.د',  'name' => 'Iraqi dinar'],
            (object) ['id' => 66,  'code' => 'ILS', 'rate' => 0, 'symbol' => '₪',    'name' => 'Israeli new shekel'],
            (object) ['id' => 67,  'code' => 'JMD', 'rate' => 0, 'symbol' => '$',    'name' => 'Jamaican dollar'],
            (object) ['id' => 68,  'code' => 'JPY', 'rate' => 0, 'symbol' => '¥',    'name' => 'Japanese yen'],
            (object) ['id' => 69,  'code' => 'JOD', 'rate' => 0, 'symbol' => 'د.ا',  'name' => 'Jordanian dinar'],
            (object) ['id' => 70,  'code' => 'KZT', 'rate' => 0, 'symbol' => '₸',    'name' => 'Kazakhstani tenge'],
            (object) ['id' => 71,  'code' => 'KES', 'rate' => 0, 'symbol' => 'Sh',   'name' => 'Kenyan shilling'],
            (object) ['id' => 72,  'code' => 'KWD', 'rate' => 0, 'symbol' => 'د.ك',  'name' => 'Kuwaiti dinar'],
            (object) ['id' => 73,  'code' => 'KGS', 'rate' => 0, 'symbol' => 'лв',   'name' => 'Kyrgyzstani som'],
            (object) ['id' => 74,  'code' => 'LAK', 'rate' => 0, 'symbol' => '₭',    'name' => 'Lao kip'],
            (object) ['id' => 75,  'code' => 'LBP', 'rate' => 0, 'symbol' => 'ل',    'name' => 'Lebanese pound'],
            (object) ['id' => 76,  'code' => 'LSL', 'rate' => 0, 'symbol' => 'L',    'name' => 'Lesotho loti'],
            (object) ['id' => 77,  'code' => 'LRD', 'rate' => 0, 'symbol' => '$',    'name' => 'Liberian dollar'],
            (object) ['id' => 78,  'code' => 'LYD', 'rate' => 0, 'symbol' => 'ل.د',  'name' => 'Libyan dinar'],
            (object) ['id' => 79,  'code' => 'LTL', 'rate' => 0, 'symbol' => 'Lt',   'name' => 'Lithuanian litas'],
            (object) ['id' => 80,  'code' => 'MOP', 'rate' => 0, 'symbol' => 'P',    'name' => 'Macanese pataca'],
            (object) ['id' => 81,  'code' => 'MKD', 'rate' => 0, 'symbol' => 'ден',  'name' => 'Macedonian denar'],
            (object) ['id' => 82,  'code' => 'MGA', 'rate' => 0, 'symbol' => 'Ar',   'name' => 'Malagasy ariary'],
            (object) ['id' => 83,  'code' => 'MWK', 'rate' => 0, 'symbol' => 'MK',   'name' => 'Malawian kwacha'],
            (object) ['id' => 84,  'code' => 'MYR', 'rate' => 0, 'symbol' => 'RM',   'name' => 'Malaysian ringgit'],
            (object) ['id' => 85,  'code' => 'MVR', 'rate' => 0, 'symbol' => 'ރ',    'name' => 'Maldivian rufiyaa'],
            (object) ['id' => 86,  'code' => 'MRO', 'rate' => 0, 'symbol' => 'UM',   'name' => 'Mauritanian ouguiya'],
            (object) ['id' => 87,  'code' => 'MUR', 'rate' => 0, 'symbol' => '₨',    'name' => 'Mauritian rupee'],
            (object) ['id' => 88,  'code' => 'MXN', 'rate' => 0, 'symbol' => '$',    'name' => 'Mexican peso'],
            (object) ['id' => 89,  'code' => 'MDL', 'rate' => 0, 'symbol' => 'L',    'name' => 'Moldovan leu'],
            (object) ['id' => 90,  'code' => 'MNT', 'rate' => 0, 'symbol' => '₮',    'name' => 'Mongolian tugrik'],
            (object) ['id' => 91,  'code' => 'MAD', 'rate' => 0, 'symbol' => 'د.م.', 'name' => 'Moroccan dirham'],
            (object) ['id' => 92,  'code' => 'MZN', 'rate' => 0, 'symbol' => 'MT',   'name' => 'Mozambican metical'],
            (object) ['id' => 93,  'code' => 'MMK', 'rate' => 0, 'symbol' => 'Ks',   'name' => 'Myanma kyat'],
            (object) ['id' => 94,  'code' => 'NAD', 'rate' => 0, 'symbol' => '$',    'name' => 'Namibian dollar'],
            (object) ['id' => 95,  'code' => 'NPR', 'rate' => 0, 'symbol' => '₨',    'name' => 'Nepalese rupee'],
            (object) ['id' => 96,  'code' => 'ANG', 'rate' => 0, 'symbol' => 'ƒ',    'name' => 'Netherlands Antillean guilder'],
            (object) ['id' => 97,  'code' => 'TWD', 'rate' => 0, 'symbol' => '$',    'name' => 'New Taiwan dollar'],
            (object) ['id' => 98,  'code' => 'NZD', 'rate' => 0, 'symbol' => '$',    'name' => 'New Zealand dollar'],
            (object) ['id' => 99,  'code' => 'NIO', 'rate' => 0, 'symbol' => 'C$',   'name' => 'Nicaraguan córdoba'],
            (object) ['id' => 100, 'code' => 'NGN', 'rate' => 0, 'symbol' => '₦',    'name' => 'Nigerian naira'],
            (object) ['id' => 101, 'code' => 'KPW', 'rate' => 0, 'symbol' => '₩',    'name' => 'North Korean won'],
            (object) ['id' => 102, 'code' => 'NOK', 'rate' => 0, 'symbol' => 'kr',   'name' => 'Norwegian krone'],
            (object) ['id' => 103, 'code' => 'OMR', 'rate' => 0, 'symbol' => 'ر.ع.', 'name' => 'Omani rial'],
            (object) ['id' => 104, 'code' => 'PKR', 'rate' => 0, 'symbol' => '₨',    'name' => 'Pakistani rupee'],
            (object) ['id' => 105, 'code' => 'PAB', 'rate' => 0, 'symbol' => 'B/.',  'name' => 'Panamanian balboa'],
            (object) ['id' => 106, 'code' => 'PGK', 'rate' => 0, 'symbol' => 'K',    'name' => 'Papua New Guinean kina'],
            (object) ['id' => 107, 'code' => 'PYG', 'rate' => 0, 'symbol' => '₲',    'name' => 'Paraguayan guaraní'],
            (object) ['id' => 108, 'code' => 'PEN', 'rate' => 0, 'symbol' => 'S/.',  'name' => 'Peruvian nuevo sol'],
            (object) ['id' => 109, 'code' => 'PHP', 'rate' => 0, 'symbol' => '₱',    'name' => 'Philippine peso'],
            (object) ['id' => 110, 'code' => 'PLN', 'rate' => 0, 'symbol' => 'zł',   'name' => 'Polish złoty'],
            (object) ['id' => 111, 'code' => 'QAR', 'rate' => 0, 'symbol' => 'ر.ق',  'name' => 'Qatari riyal'],
            (object) ['id' => 112, 'code' => 'RON', 'rate' => 0, 'symbol' => 'L',    'name' => 'Romanian new leu'],
            (object) ['id' => 113, 'code' => 'RUB', 'rate' => 0, 'symbol' => 'руб.', 'name' => 'Russian rouble'],
            (object) ['id' => 114, 'code' => 'RWF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'Rwandan franc'],
            (object) ['id' => 115, 'code' => 'SHP', 'rate' => 0, 'symbol' => '£',    'name' => 'Saint Helena pound'],
            (object) ['id' => 116, 'code' => 'WST', 'rate' => 0, 'symbol' => 'T',    'name' => 'Samoan tala'],
            (object) ['id' => 117, 'code' => 'SAR', 'rate' => 0, 'symbol' => 'ر.س',  'name' => 'Saudi riyal'],
            (object) ['id' => 118, 'code' => 'RSD', 'rate' => 0, 'symbol' => 'дин.', 'name' => 'Serbian dinar'],
            (object) ['id' => 119, 'code' => 'SCR', 'rate' => 0, 'symbol' => '₨',    'name' => 'Seychelles rupee'],
            (object) ['id' => 120, 'code' => 'SLL', 'rate' => 0, 'symbol' => 'Le',   'name' => 'Sierra leonean leone'],
            (object) ['id' => 121, 'code' => 'SGD', 'rate' => 0, 'symbol' => '$',    'name' => 'Singapore dollar'],
            (object) ['id' => 122, 'code' => 'SBD', 'rate' => 0, 'symbol' => '$',    'name' => 'Solomon Islands dollar'],
            (object) ['id' => 123, 'code' => 'SOS', 'rate' => 0, 'symbol' => 'Sh',   'name' => 'Somali shilling'],
            (object) ['id' => 124, 'code' => 'ZAR', 'rate' => 0, 'symbol' => 'R',    'name' => 'South African rand'],
            (object) ['id' => 125, 'code' => 'KRW', 'rate' => 0, 'symbol' => '₩',    'name' => 'South Korean won'],
            (object) ['id' => 126, 'code' => 'LKR', 'rate' => 0, 'symbol' => 'Rs',   'name' => 'Sri Lankan rupee'],
            (object) ['id' => 127, 'code' => 'SDG', 'rate' => 0, 'symbol' => '£',    'name' => 'Sudanese pound'],
            (object) ['id' => 128, 'code' => 'SRD', 'rate' => 0, 'symbol' => '$',    'name' => 'Surinamese dollar'],
            (object) ['id' => 129, 'code' => 'SZL', 'rate' => 0, 'symbol' => 'L',    'name' => 'Swazi lilangeni'],
            (object) ['id' => 130, 'code' => 'SEK', 'rate' => 0, 'symbol' => 'kr',   'name' => 'Swedish krona'],
            (object) ['id' => 131, 'code' => 'CHF', 'rate' => 0, 'symbol' => 'Fr',   'name' => 'Swiss franc'],
            (object) ['id' => 132, 'code' => 'SYP', 'rate' => 0, 'symbol' => 'ل.س',  'name' => 'Syrian pound'],
            (object) ['id' => 133, 'code' => 'STD', 'rate' => 0, 'symbol' => 'Db',   'name' => 'São Tomé and Príncipe dobra'],
            (object) ['id' => 134, 'code' => 'TJS', 'rate' => 0, 'symbol' => 'ЅМ',   'name' => 'Tajikistani somoni'],
            (object) ['id' => 135, 'code' => 'TZS', 'rate' => 0, 'symbol' => 'Sh',   'name' => 'Tanzanian shilling'],
            (object) ['id' => 136, 'code' => 'THB', 'rate' => 0, 'symbol' => '฿',    'name' => 'Thai baht'],
            (object) ['id' => 137, 'code' => 'TOP', 'rate' => 0, 'symbol' => 'T$',   'name' => 'Tongan paʻanga'],
            (object) ['id' => 138, 'code' => 'TTD', 'rate' => 0, 'symbol' => '$',    'name' => 'Trinidad and Tobago dollar'],
            (object) ['id' => 139, 'code' => 'TND', 'rate' => 0, 'symbol' => 'د.ت',  'name' => 'Tunisian dinar'],
            (object) ['id' => 140, 'code' => 'TRY', 'rate' => 0, 'symbol' => 'T',    'name' => 'Turkish lira'],
            (object) ['id' => 141, 'code' => 'TMT', 'rate' => 0, 'symbol' => 'm',    'name' => 'Turkmenistani manat'],
            (object) ['id' => 142, 'code' => 'UGX', 'rate' => 0, 'symbol' => 'Sh',   'name' => 'Ugandan shilling'],
            (object) ['id' => 143, 'code' => 'UAH', 'rate' => 0, 'symbol' => '₴',    'name' => 'Ukrainian hryvnia'],
            (object) ['id' => 144, 'code' => 'AED', 'rate' => 0, 'symbol' => 'د.إ',  'name' => 'United Arab Emirates dirham'],
            (object) ['id' => 145, 'code' => 'GBP', 'rate' => 0, 'symbol' => '£',    'name' => 'United Kingdom pound sterling'],
            (object) ['id' => 146, 'code' => 'USD', 'rate' => 0, 'symbol' => '$',    'name' => 'United States dollar'],
            (object) ['id' => 147, 'code' => 'UYU', 'rate' => 0, 'symbol' => '$',    'name' => 'Uruguayan peso'],
            (object) ['id' => 148, 'code' => 'UZS', 'rate' => 0, 'symbol' => 'лв',   'name' => 'Uzbekistan som'],
            (object) ['id' => 149, 'code' => 'VUV', 'rate' => 0, 'symbol' => 'Vt',   'name' => 'Vanuatu vatu'],
            (object) ['id' => 150, 'code' => 'VEF', 'rate' => 0, 'symbol' => 'BsF',  'name' => 'Venezuelan bolívar fuerte'],
            (object) ['id' => 151, 'code' => 'VND', 'rate' => 0, 'symbol' => '₫',    'name' => 'Vietnamese dong'],
            (object) ['id' => 152, 'code' => 'YER', 'rate' => 0, 'symbol' => '﷼',    'name' => 'Yemeni rial'],
            (object) ['id' => 153, 'code' => 'ZMW', 'rate' => 0, 'symbol' => 'ZK',   'name' => 'Zambian kwacha'],
        ];
    }
}
